### ISSUE TITLE
Arch Linux compilation

### ISSUE THREAD

**Issue by mpbraendli** [kb1vc/SoDaRadio#4]
Hi,
On my system, I had to apply this patch to get working compilation.
The qwt 6.1.3 library is called `libqwt.so`, not `libqwt-qt5.so` (I guess) here, and there were missing includes g++ 8.1.1 complains about. Also, linking failed because of pthreads. CMake version is 3.11.4, boost 1.67.0.

[compile-archlinux.patch.txt](https://github.com/kb1vc/SoDaRadio/files/2120411/compile-archlinux.patch.txt)

It now compiles, FM transmit seems to work, but I haven't been able to receive anything with my B200 yet.

73
Matthias

**Comment by kb1vc** [comment]
The build problems were fixed in commit: 

> commit dbc4f2d2581df7578600d7117d4f912735a542a2 (arch_linux_patch)
> Author: Matt Reilly <kb1vc@kb1vc.org>
> Date:   Mon Aug 13 20:58:31 2018 -0400
> 
>     Applied patches from a user -- thank you Matthias
>     
>     fixed compilation problem with Command.cxx and problems with
>     thread and libqwt dependencies on arch linux
